version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    labels:
      - "💾 dependencies"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "💾 dependencies" 
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "💾 dependencies"
    schedule:
      interval: "daily"
